### ISSUE TITLE
Crash for HxC Enchant 1.6

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#10]
I'm getting a nullpointer with the 1.6 update: http://pastebin.com/LwGN7Bmx

Also, the Penetrate and Piercing Enchants are not working correctly. I do the same amount of damage to armored targets at all levels of the enchant as well as the same damage without it.

Take care

**Comment by DrZed** [comment]
Yeah I gotta fix that wait a moment... Also Those enchants I don't think are broken but they're hard to test so let me do some testing

**Comment by ReportBot9009** [comment]
Ya, I understand they are hard to test. My modded game has roguelike dungeons which has armored mob spawners, so it's easy for me to test it in my game. The mob spawners range from chain to diamond armor. Also, is one for the bow and arrow?

**Comment by DrZed** [comment]
Piercing is sword Penetrating is arrow (or backwards IDK)

**Comment by ReportBot9009** [comment]
Haha! Well, I've tried both on both and it doesn't change, so I'm not sure either XD

**Comment by DrZed** [comment]
WOW I FAILED BIG TIME

**Comment by DrZed** [comment]
if (Config.enchPiercingEnable) {
                PiercingLevel = EnchantmentHelper.getEnchantmentLevel(Enchants.Piercing.effectId, item);
                if (PiercingLevel > 0) Victim.attackEntityFrom(new DamageSource("Piercing").setDamageBypassesArmor(), Config.PiercingDamage);
            }
yet config is never set so the value is 0

**Comment by ReportBot9009** [comment]
Oh dang! Whoops! Nice catch :)

**Comment by DrZed** [comment]
Here ya go or wait 10 minutes for Curse
http://puu.sh/iq7y0.jar

**Comment by ReportBot9009** [comment]
Awesome! Thank you so much :)
