### ISSUE TITLE
Server Crash when Killing Thaumcraft Angry Zombie - with Extra Utilities Sword Enchanted with Vampirism

### ISSUE THREAD

**Issue by plazia** [HxCKDMS/HxCEnchants#11]
HxCEnchants{1.7.10-1.6.2} [HxC Enchants](HxCEnchants-1.7.10-1.6.2.jar) 
HxCCore-ASM{1.5.0} [HxCKDMS Core ASM](minecraft.jar) 

Hi there - I've really been enjoying this mod - love all the enchants but had a server crash last night. Was killing a Thaumcraft angry zombie with the extra utilities sword I'd enchanted with (I think Vampirism) and upon death the server crashed with this. It appears to reference your mod.

Crash report here.

http://pastebin.com/wXXFZSt9

**Comment by DrZed** [comment]
Thank you this is what' I've been waiting for
A bug report :D

**Comment by DrZed** [comment]
Are you using anything that modifies the hunger system?
\ if (curFood < 40 && newFood < 40) Attacker.getFoodStats().setFoodLevel(Math.round(newFood));
That's what crashed

**Comment by DrZed** [comment]
Anyway I suggest removing the Vampirisim enchant from your weapon and from the game, I'll look further into this at a time I'm not tired/hungry.
