### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#12]
Hello,

I just installed the new 1.7.0 and as usual with any enchant mods, I took off my armor and weapons threw them away because of the updates usually conflicting. 

I then walked to the other side of my base ~15 seconds and jumped to place a block and the crash happened right as I jumped.

http://pastebin.com/5Qb1LZxV

**Comment by DrZed** [comment]
THANK YOU :D

**Comment by DrZed** [comment]
@ReportBot9009 What's you're MC UUID or username I wanna stick [HxCHelper] by your name

**Comment by ReportBot9009** [comment]
Nah, don't worry about it :). I'd rather remain anonymous and just help from the shadows ;).

Thanks for getting that update out so quickly!
