### ISSUE TITLE
Armor Event Handler Jump Crash

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#14]
I don't think this is fixed yet: http://pastebin.com/3pEyb2VZ

This was wearing steel boots, leggings and helmet from railcraft.

**Comment by DrZed** [comment]
2 things
1 did you delete your configs
2 did u disable jumpboost?

**Comment by ReportBot9009** [comment]
Hi DrZed,

Yes, I deleted my configs for the 1.7.0 update, so they were new configs as of that version.

In the new configs, I did disable jumpboost.

**Comment by DrZed** [comment]
I saw 
Yeah It's one of the few enchants I forgot to add a check ;/

**Comment by ReportBot9009** [comment]
Ahh. There's always one, lol!

**Comment by ReportBot9009** [comment]
I guess while I have you here I can ask you one more question. What is the "Special" next to cost in the configs?

**Comment by DrZed** [comment]
so far only 3 have special
Rate of checks for regen/repair/iforgot
higher = slower

**Comment by ReportBot9009** [comment]
Gotcha. Thanks :)
