### ISSUE TITLE
Ticking player -> Armor Handler Crash

### ISSUE THREAD

**Issue by accessdenied0** [HxCKDMS/HxCEnchants#15]
Dear @DrZed,

I got this strange crash with the newest version of this mod. After a random time in my base (moving or just standing still) the game froze and crashes with this message: http://pastebin.com/gQy8Cpfn

hope you can help,

access_denied

**Comment by karelmikie3** [comment]
your HxC Enchants is outdated please update to the latest version and see if it still happens.

**Comment by DrZed** [comment]
Shoul've been fixed in build 2.0.1 and latest is 2.0.2 Also Law :D I hope he beats Doffy :0 as well thank you for at least attempting to report a bug XD
