### ISSUE TITLE
Magnet X

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#16]
Crash when I first mined a block with Magnet X

http://pastebin.com/c4w62NaR

**Comment by DrZed** [comment]
Did you mine a block with bare hands?

**Comment by DrZed** [comment]
Also Magnet has nothing to do with mining
It only is an aura enchant that magnetises stuff to us

**Comment by DrZed** [comment]
http://puu.sh/jlMTA.jar

**Comment by ReportBot9009** [comment]
Haha, yes I'm aware it is an enchantment and not a tool, lol! I just started a world, enchanted a piece of armor and broke a dirt block with my hand to see if it would bring it to me at a distance. As soon as it broke it crashed. Seems you've fixed it :)

**Comment by DrZed** [comment]
Yeah I forgot to make sure I check only when an enchanted item is in hand
not all the time
