### ISSUE TITLE
Not an issue, but a request!

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#17]
Well, I've noticed with a lot of enchant mods that add "swiftness" or a faster running effect, the camera does this zoom back in out to make it appear you are running much faster. Now, add the AdrenalineBoost enchant, and all of a sudden your FOV is 120+ and you can barely see anything in front of you. It makes it very difficult to see. 

I was wondering if you could somehow disable that zoom/fisheye effect when the AdrenalineBoost enchant is casted?

**Comment by DrZed** [comment]
I'll work on doing a FoV tweak on it...

**Comment by DrZed** [comment]
This is client side render code I'm having to really learn that XD I'm not good with render code...

**Comment by DrZed** [comment]
I redid the swiftness thing, it still does fov shiz because it's default minecraft code...
