### ISSUE TITLE
Enchants not working

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#18]
First, I turned the charges system off, does this disable all of the enchants?

I don't think most of your enchants are working at all in the 2.0.5 version.

Repair, regen, swiftness, magnet, divine intervention.

**Comment by DrZed** [comment]
I tested they all work with charge sys on
lemme test with them off
:\ why not use my charges system :\ OP enchants need balance featrues

**Comment by ReportBot9009** [comment]
I understand they do need some balance, but I have Enchanting Plus installed and have changed the XP amount to enchant things extremely high to balance. Me personally, I really like having higher enchant cost than maintenance =\ 

And don't get me wrong, I'm more of a gregtech style grindy mod user, where I like the grind. But enchants server a different purpose for me when I finally achieve them =)

**Comment by ReportBot9009** [comment]
Also, I want to explain what is happening in the enchant table from Enchanting Plus. When I put an enchant on, then leave the table and say come back with enough XP for another enchant, as soon as I put the item (armor/weapon etc.) back in the table, the enchantment disappears. Not sure if this is you or not, but the other enchanting mods I have on are not doing this. 

Also, I feel there is something buggy going on with all the enchants that go higher than IX.

**Comment by DrZed** [comment]
I'll look into this later I'm quite tired

**Comment by DrZed** [comment]
Check in latest version!

**Comment by ReportBot9009** [comment]
Just checked. None of the enchants are working. Just to be sure, swiftness is on the leggings and not boots?

**Comment by ReportBot9009** [comment]
Do I need to put the charge on each enchant to 0 as well as turn the charge system off? At least for right now to test them...

**Comment by ReportBot9009** [comment]
Ok, gluttony is working. To make sure, you don't want the hunger bar to refill all the way. It only fills 8 bars at level 21, correct?

**Comment by ReportBot9009** [comment]
Not sure what "EnchantLeech" does. What I think it does is add food or health upon hitting an animal or mob, but it's not doing either.

**Comment by ReportBot9009** [comment]
I hope you don't mind all the comments. I'm just updating as I go down the list. If you want me to consolidate, I will.

**Comment by DrZed** [comment]
Just set the boolean to false.... don't modify the requirements...
Send me a copy of your config...

**Comment by DrZed** [comment]
Enchant Leech doesn't work
it has no code

**Comment by ReportBot9009** [comment]
Config File: http://pastebin.com/6H44Rvpz

**Comment by ReportBot9009** [comment]
Haha, ok ok, meteor fall is amazing! Nice work :)

**Comment by DrZed** [comment]
I just tested thank you for reporting I decided to break it down line by line and found why vit and swift may not work

**Comment by ReportBot9009** [comment]
This is what I'm talking about with your enchantments. As you can see I have Meteor Fall X enchanted on the boots. In the enchanting table, it shows the level at 0, unlike vanilla or other enchant mods. Not sure if you are going for this, but with Enchanting Plus, I have to enchant the item from 0 instead of from 2 or 3 or whatever enchant level I have at the time. 

Enchanted Boots: http://i.imgur.com/8Pnzqiw.jpg
Enchanting Table: http://i.imgur.com/dP38KAV.png
Vanilla and Modded Enchants: http://i.imgur.com/opJiupw.png

**Comment by DrZed** [comment]
What other enchants are broked?

**Comment by DrZed** [comment]
I don't know what's happening lemme get a dev build of Enchanting plus added to my env and check what's happening

**Comment by ReportBot9009** [comment]
Well, none of the auras are working correctly. I mean, when I first installed the 2.0 version I had them all turned on and tested it out. None were working. I do have the Ice Aura set to true as of right now and from what I can tell, it doesn't do anything.

Some serious documentation would be nice. I know a lot of mod authors love to let the players explore and find things out with their mods without having to tell them what things do, but maybe on your website or wiki you can get better detailed information. Just saying, but you do what you feel is right :).

**Comment by ReportBot9009** [comment]
Ya, Enchanting Plus is a staple in my modpacks. Just one of those types of mods that you personally enjoy.

**Comment by DrZed** [comment]
You need all 4 pieces of armour with the aura enchants on them

**Comment by ReportBot9009** [comment]
Vampirism is working. Regen is working, stealth is not, swiftness is not, jumpboost is good!, thick and fiery are good!, (testing on mobs) dark and toxic do not do anything to mobs, deadly is well, deadly(working great!), repulsive aura working great, healing aura heals passive mobs like horses, if so, working great, no idea what Gaia's aura does, maybe farms? Yep, looks like it's good for growing them crops! Working!

Ok, I'm turning everything on and testing the Auras

**Comment by DrZed** [comment]
Stealth?_?
Well I found out by looking in EPlus code
I cannot make my enchants work in its table....
I will need to modify EPlus or revert to my old way of enchants of which I am not doing...
So yeah blacklisting my enchants from EPlus

**Comment by DrZed** [comment]
Do you even know how stealth works?

**Comment by DrZed** [comment]
ReportBot!!!!!!! I fixed compat with EPlus :D
