### ISSUE TITLE
Crash With Buildcraft Mining Well

### ISSUE THREAD

**Issue by RoloEdits** [HxCKDMS/HxCEnchants#19]
http://pastebin.com/tLHPSdEK 

crashes when the mining well mines

**Comment by RoloEdits** [comment]
also just got the same crash but for punching a mushroom with bare hand

**Comment by karelmikie3** [comment]
this could be fixed please update to the latest build of HxC-Enchants (2.0.5) and test if the crash happens.

**Comment by RoloEdits** [comment]
yes it is fixed in 2.0.5.

sorry for the trouble there has been a lot of updates lately hard to keep track :)

**Comment by DrZed** [comment]
Fixed in 2.1.0 as well
