### ISSUE TITLE
Swiftness enchant is broken

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#2]
It seems like the swiftness enchant is broken because right now it is making my screen zoom out and in every second.

**Comment by DrZed** [comment]
Sorry about the troubles will look into immediately.

**Comment by DrZed** [comment]
This happens often when I code at 4am

**Comment by DrZed** [comment]
Fixed Thank you!
http://puu.sh/hKkSx.jar

**Comment by EnderSam** [comment]
Well it seems like what ever you did, is know kicking me from my server after putting swiftness on pants
