### ISSUE TITLE
Did i do anything wrong? :O!!! 

### ISSUE THREAD

**Issue by Beanius** [HxCKDMS/HxCEnchants#20]
Killed a mob and my game crashed? :D
http://pastebin.com/ksYSMMMk

**Comment by DrZed** [comment]
Fixed in latest version http://minecraft.curseforge.com/mc-mods/227599-hxcenchants/files

**Comment by Beanius** [comment]
Thanks alot! ^^,

**Comment by DrZed** [comment]
:P A lot*

**Comment by Beanius** [comment]
Ohhh yooouuu!! hahah ;D<3
