### ISSUE TITLE
Enchants Not Showing Up In Enchanting Plus Table After Updating To HxCEnchants-1.7.10-2.1.2

### ISSUE THREAD

**Issue by RoloEdits** [HxCKDMS/HxCEnchants#21]
After updating none of your enchants are showing up in the enchanting plus enchanting table.
Not sure what else I should provide so please ask if you need anything.

**Comment by DrZed** [comment]
Not a bug, but a feature you can remove the enchants from the blacklist in the config files of Eplus but I wouldn't use it You can apply my enchants LAST but don't meddle with enchants after... My enchants get removed when you enchant with EPlus table :\ it's a bug on their side

**Comment by RoloEdits** [comment]
I'm afraid i'm still confused, none of the enchants are blacklisted in the EPlus config.And I don't mean the enchants are disappearing there not even showing up as an option to select, sorry for the confusion.

**Comment by DrZed** [comment]
Yeah I blacklisted them in code I thought it was in configs but nvm it's default blacklisted in code I'll add an option to remove blacklist BUT I won't support any issues reguarding the enchants being removed...

**Comment by RoloEdits** [comment]
OK thanks for clearing that up :)

**Comment by DrZed** [comment]
Fixed compat with EPlus

**Comment by RoloEdits** [comment]
thank you
