### ISSUE TITLE
Crash on keybindings in minecraft with HXCenchants

### ISSUE THREAD

**Issue by plazia** [HxCKDMS/HxCEnchants#22]
Client is crashing when I go to keybindings - all and before I can even attempt to scroll it's just crashing.

Removing your mod eliminates the issue.

Crash report here
http://pastebin.com/NrjFeXW2

Also really loving the new enchants you've added and all the bugs you've fixed. I have just one question. This XP Infuser seems awesome but are you going to make it so we can actually craft it in survival - I can't see any recipe anywhere in NEI. Another tweak that would be handy is inventory tweaks/mouse tweaks support whereby we can shift click items from our inventory into it's inventory/slot?

Also I'm an avid fan of EnchantingPlus. I noticed you blacklisted the enchants from that mod but at least you gave us the option to disable that and for that I am grateful to you.

peace.

**Comment by DrZed** [comment]
modwarriors.notenoughkeys.gui.GuiControlsOverride
Not my fault it crashed (not entirely) Not enough keys breaks several mods that I know of with keybinds I'll find a way to fix it but for now Just disable enchants (OverCharge, FlashStep)
Sorry I forgot to add the recipe for XP infuser also
" noticed you blacklisted the enchants from that mod but at least you gave us the option to disable that and for that I am grateful to you."
Be grateful as you wish there is a known but with it I want to let you know DON'T apply my enchants until after you get your enchants you want on your armor My enchants get removed every time you change enchants using EPlus

**Comment by DrZed** [comment]
Disabling the enchants disable the keybinds that go with them
