### ISSUE TITLE
HxC Enchants 2.1.6 & Core 1.8.0: Enchantment Swiftness not working

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#24]
I tried to enchant some leggings with Swiftness IV using the EPlus table. That worked. The Enchantment Swiftness IV was added to the leggings.
I charged the leggings using the XP Infuser.
The problem is that there is no effect. The movement speed does not increase as expected.
Please check that out.

**Comment by DrZed** [comment]
kk

**Comment by walkerjonny** [comment]
Sorry, I'm not good with shortcuts.
What does "kk" mean?

**Comment by DrZed** [comment]
nothing at all XD

**Comment by DrZed** [comment]
Fixed this 4 days ago xD
