### ISSUE TITLE
Question about gluttony enchant. Warning I can't english!

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#26]
R U really heal up like an apple, but remove something like meat?
player.getFoodStats().addStats(((ItemFood) Items.apple).getHealAmount(new ItemStack(tmp.get(true))), ((ItemFood) Items.apple).getSaturationModifier(new ItemStack(tmp.get(true))));

if (player.inventory.mainInventory[slot] != null && player.inventory.mainInventory[slot].getItem() instanceof ItemFood && player.inventory.mainInventory[slot].getItem() == tmp.get(true)) {
                        player.inventory.decrStackSize(slot, 1);

**Comment by adamsonich** [comment]
sorry, problems with reading ability :-)

**Comment by karelmikie3** [comment]
Lol

**Comment by DrZed** [comment]
FYI for future people I use apple just to get the methods
