### ISSUE TITLE
[V3]Charm Items to store Charges/Enchants

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#28]
make item like paper enchatable. 
so if paper anchanted with LifeSteal, then "proc" LifeSteal enchant mechanics.
and of course make it multi enchantable.

**Comment by DrZed** [comment]
You what mate? Learn to use english, as well as explain.

**Comment by adamsonich** [comment]
I want an item for enchanting, so enchant it with Ur enchants/charges and hold in inventory and not look for charges on 4 items of armor, and dont enchant several sets of armor.

**Comment by DrZed** [comment]
Again learn to speak english, let me attempt to clarify what you're asking.
If you can't speak english, 日本語 話すことを学ば
1. Ability to enchant a seperate item (Charm), and have it work from being in the inventory.
2. Ability to charge Armour/Tools with charges on seperate item?
3. Don't make armour enchantable?

**Comment by adamsonich** [comment]
1 and 2 are options I am asking.

**Comment by DrZed** [comment]
Which enchants do you want to work from say an item like a "Charm"?
1. Aura Enchants?
2. Damage Based Enchants?
3. Protection Enchants?
4. All?

As for having armour/tools draining from the charge?
- Wait for my new Ideas to come to fruition.. :P
  - Charms won't be added til v3

**Comment by adamsonich** [comment]
for me better option 4. May be separate it: aura charms, damage charms, protection charms. But it's all in Ur hands.
with part 2: how many updates till v3?

**Comment by DrZed** [comment]
I plan to add a custom Enchanting system, Ritualistic Style. Don't worry as all things I do it will be configurable. Vanilla enchants and such will also be applied this way, and mod enchants as I find them will as well.

This way enchants will be re-apply-able and removable. As for charm for storing charges? Sounds good I'll add multiple charm types each with a select amount of max charges (wooden being least).

Aura Enchants via Charms? Maybe I'll think about it when coding, part of the balance was requiring it on all pieces of armour.

Damage Enhance enchants on Charms? I don't think so, it'd make mods not be able to use my enchants in, SlaughterBlock from my mod, Grinder from EnderIO, etc..

Protection enchants? Maybe some.

I'll be adding 4 charm slots to the player inventory as well. :P

**Comment by adamsonich** [comment]
Sounds good. :-)

**Comment by DrZed** [comment]
@adamsonich What's your minecraft username? I'd like to put [HxCSupporter] by your name, would you accept?

**Comment by adamsonich** [comment]
Yes. Thanks. My username is adamsonich

**Comment by DrZed** [comment]
BTW I added you to the list so you should be able to see HxCSupporter in red in game from now on, in chat and above your head... so long as the core is installed on the client
