### ISSUE TITLE
regen work incorrectly

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#29]
tryed regen on leggings, it's use charges from chest armor. 

so, in source U have:
 if (player.inventory.armorItemInSlot(3) != null)
                H = (short) EnchantmentHelper.getEnchantmentLevel
...
ArmourHelm = player.inventory.armorItemInSlot(3),
...
 if (ArmourHelm != null && ArmourHelm.getTagCompound() != null)
                    HChrg = ArmourHelm.getTagCompound().getLong("HxCEnchantCharge");
...
if (H > 0 && (CChrg > (hp \* 2) / Regen || !Configurations.enableChargesSystem)) {
                    if (Configurations.enableChargesSystem)
                        ArmourChest.getTagCompound().setLong("HxCEnchantCharge",

**Comment by DrZed** [comment]
Are you stupid? your quote is all helmet...

**Comment by DrZed** [comment]
Anyway it wasn't working properly since I had the wrong order >_>. BUT if you were thinking H was legs or armor in slot 3 was supposed to be legs you're wrong.
H=Helmet
slots in minecraft code go from boots(0)->Helm(3)

**Comment by adamsonich** [comment]
I don't even think that H is helmet/chest/leggens/boots. I wrote what I found. So when I found problem I went to Ur repository and found some lines with incorrect logic. I wrote it. And it's all. 
Thank U.
part 2 of debuging:
H is Helmet, C is chest, L is leggins, B is boots?
U have Helmet and Chest and Chest again in /src/main/java/HxCKDMS/HxCEnchants/Handlers/EnchantHandlers.java#L342
if (H > 0 && (CChrg > (hp \* 2) / Regen || !Configurations.enableChargesSystem)) {
                    if (Configurations.enableChargesSystem)
                        ArmourChest.getTagCompound().setLong("HxCEnchantCharge", HChrg - H \* getData("Regen", "armor")[4]);

**Comment by DrZed** [comment]
Fixed thanks
