### ISSUE TITLE
Auto-Smelt issue with Metallurgy (and probably other mods)

### ISSUE THREAD

**Issue by a-rat-girl** [HxCKDMS/HxCEnchants#3]
When you mine any of the Metallurgy ores with metadata with the Auto-Smelt enchant, it will default to the smelting product of the ore with no metadata. For example, if you mine tin, which is Metallurgy:base.ore:1, it will give a copper ingot, because that's what copper (Metallurgy:base.ore:0) gives when smelted. So when you mine oreName:5, it will give the smelting output of the oreName:0, regardless of if oreName:5 gives a different output.

**Comment by DrZed** [comment]
Karel forgot something XD

**Comment by karelmikie3** [comment]
can you give this a try for me: http://puu.sh/hLPda.jar this should've fixed it.

**Comment by DrZed** [comment]
http://puu.sh/hM7mA.jar This should fix that and another bug also would you like to get [HxCHelper] beside your name if so send me your player name or player UUID

**Comment by DrZed** [comment]
Please close this issue if it was fixed for you if you don't respond within 48 hours I close this automatically
