### ISSUE TITLE
gluttony not work

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#30]
Iron helmet with gluttony V or X or XXI, 3k+ charges, stack of apples and half heard. others pieces has 2k+ charges. and toxic aura work from them.

**Comment by DrZed** [comment]
Gluttony works I've tested and even made videos on it... It reads based on your hunger, lvl 5 only heals hunger when it drops below 5 hunger

**Comment by adamsonich** [comment]
O.o, it's hunger not health, I sorry for my panic.
