### ISSUE TITLE
Stealth needs to be rewritten (DrZed)

### ISSUE THREAD

**Issue by Fortist** [HxCKDMS/HxCEnchants#31]
I decided to throw this back into my modlist to see if something had changed with other mods, as I had this problem before, but didnt care enough to troubleshoot it.

I tried to use the enchantment "Stealth"  but it seems to make my game "freeze" in the sense that everything stops moving and I cant enter any GUIs.
When quitting normally, it hangs on the "Shutting down Internal Server" text, so I have to force it to close.

I have no real idea what is causing it, and It seems to only happen when aggressive mobs are around.
A semi test I did while testing something while in The End. I was fine until Skeletons, Creepers and the like started spawning in. Reloading that world a few seconds before and removing the boots with stealth basically made it a non issue anymore.

**Comment by DrZed** [comment]
Thanks for telling me, please disable "Stealth" enchant until I fix this issue, should be fixed in next build when I re-write the Stealth enchant
