### ISSUE TITLE
EnchantHandlers.java weird logic

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#32]
"!(entity instanceof EntityPlayer)) && entity != player"
(entity is not any player) and (entity is not owner-player) will always give false on any player

**Comment by adamsonich** [comment]
small but still speed up

**Comment by DrZed** [comment]
You didn't read the whole line did you?
"(Configurations.PlayerAuraDeadly || !(entity instanceof EntityPlayer)) && entity != player"
IF PlayerAuraDeadly is enabled then the statement will be read in the code as..
"true && victim != EnchantedPlayer"
If it's not enabled
"entity != EntityPlayer && victim != enchantedPlayer"

**Comment by DrZed** [comment]
If enabled the enchant can damage players, but I don't want it damaging the user of the enchant

**Comment by DrZed** [comment]
I use IntelliJ IDEA AKA (Intelligent Java Integrated Development Environment Advanced)
It would've told me that the statement was useless, if it was.
