### ISSUE TITLE
[Request] Digger Enchant

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#33]
tool enchanted with digger will dig cubes 2x2x2/3x3x3/4x4x4/5x5x5. or level 1 dig 3 wide, level 2 3 wide and 2 tall, level 3 will dig 3x3.
And trick it before FlameTouch and VoidTouch.

**Comment by DrZed** [comment]
//        ToolEnchants.put("PipeMine", "false, 451, 4, 2, 30, 25");
I already thought about it.
Thinking of best approach to do so first.
I already had plans for it to trigger at the exact same time.

**Comment by DrZed** [comment]
How about
LVL | Effect
   1   | 3x1x1
   2   | 3x3x1
   3   | 3x3x3
   4   | 5x3x1
   5   | 5x3x3
   6   | 5x5x5
 OR
Width Enchant, Height Enchant, Depth Enchant, level being the size....
OFC Logical stuff inserted
I can't think atm tired...

**Comment by adamsonich** [comment]
5x5x5 is difficult for my imagination. and logical realization must be beautiful.

**Comment by DrZed** [comment]
5x5x5 mining will be offset infront of player

**Comment by DrZed** [comment]
Done adam, enable enchant Earth Eater and try it out :P 
After I make a way to get the enchants again xD
