### ISSUE TITLE
[v3]New Enchants: Armored, Stand and Charge shield.

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCEnchants#34]
"Armored" adds armor points to player. and eats charges over time like Vitality.
"Stand" adds armor points if player not moved 1-5-10 ticks. 
- both enchants adds up to "vanilla" 20 armor points.

"charge shield" reduce damage to player due to armor charges. not all damage, but some percent. may be by skill level: 1 - 30%, 2 - 50%, 3 - 70%

**Comment by DrZed** [comment]
Armoured - Maybe i'll look into how simple the armor system is.
Stand - not 1-5-10 ticks that's too fast, 10 ticks is half a second, maybe 20-50-100?
Charge Shield????? Maybe in V3 because in V3 default vanilla enchants will be auto removed from stuff with my enchants on it, for balance purposes, I'm not gonna remove vanilla enchanting. I'm just gonna not let it interact with someone who's using my enchants.

**Comment by DrZed** [comment]
As for "1 - 30%, 2 - 50%, 3 - 70%"
I'm thinking
5% per level max level 15?

Charge Drain being the amount of damage prevented \* 10.

{SCENARIO}
Player gets hit by zombie taking 10 damage.
Armour ticks, Damage removed is 75% meaning 3 damage actually taken
70 Charge lost from reduced damage.
{END SENARIO}

**Comment by adamsonich** [comment]
Sounds good. And scenario is good too.

**Comment by walkerjonny** [comment]
Do you plan to add the possibility to allow interaction between your enchants and vanilla or other mod enchants in V3 as an option in the config file or do you just want to avoid double enchant interaction with that like Homing from your mod and Homing from other mods for example?
I for myself won't be happy if I can't for example add the vanilla enchant Protection and Unbreaking to my boots if I want to add the Flight Enchantment from HxCEnchants. Such kind of interaction makes the real fun for me. If I have to choose between your Enchants and Vanilla and other mods Enchants that would just kill the fun for me.
But blocking the ability to add double Enchants like Homing, Swiftness or Venom from different mods makes good sense.

**Comment by DrZed** [comment]
I was going to detect other mod enchants and remove them from the enchant array (configurable of course..)
