### ISSUE TITLE
Wither Protection (Ticking Player)

### ISSUE THREAD

**Issue by RoloEdits** [HxCKDMS/HxCEnchants#35]
http://pastebin.com/icdf0bz7

I'm getting this crash when fight the Gaia guardian and when falling into sludge pools.I tried identical helmets just one with the wither protection and one without it and i'm getting this crash with the one that has it and not with the one that doesn't have it.

**Comment by DrZed** [comment]
Mkay... gotta figure a different way for that enchant to work then
Just disable the enchant...

**Comment by RoloEdits** [comment]
OK, Thanks.

**Comment by DrZed** [comment]
Making it cancel the damage, instead of remove the effect...

**Comment by RoloEdits** [comment]
OK thanks:)
