### ISSUE TITLE
XPInfuser Packet and HxCEnchanter Packet ID Conflict

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#37]
Fastcraft & NotEnoughIDs are working together to extend the block ID limit up to 31999, especially in the combination above.
To reach this goal the block IDs need to use full two bytes now - both in RAM and especially within the save files. As I know NEID handles that
Unfortunately I'm getting this error now when I try to infuse XP into a given item like a armor part with the XP infuser:
http://pastebin.com/Yqf9QDcG
The server shuts down and points you back to the menu.
Because the error code there lets assume that your mod does also stuff at byte level there might be an issue with the mods above, especially when they are combined.
Maybe you want to have a look into it.

**Comment by DrZed** [comment]
Thanks, will look into that.

**Comment by DrZed** [comment]
Report this to NotEnoughIDs as well I'm not sure they tweak CPW's ByteBufUtils

**Comment by walkerjonny** [comment]
I'll do that right now

**Comment by DrZed** [comment]
Which version of HxCEnchants?

**Comment by walkerjonny** [comment]
I wanted to have some clearer insights before posting this to the NEID issue tracker, so I did some further tests. Here are the results:
That issue starts with HxC Enchants 2.2.0 and persists with HxC Enchants 2.2.1.
HxC Enchants 2.1.8 works fine so far.
I also checked this out with an older combination of Fastcraft 1.22 ctest13 and NotEnoughIDs 1.2.0. The results were the same.
Possibly there might be some code changes between 2.1.8 and 2.2.0 which are causing that issue.
As I see you have introduced the HxC Enchanter at 2.2.0. Could be some code interactions there.

**Comment by DrZed** [comment]
I'll look further into that

**Comment by DrZed** [comment]
It has nothing to do with them, it's a fail on my side.

**Comment by walkerjonny** [comment]
Thank you for fixing it that fast!

**Comment by DrZed** [comment]
I try my best to not let a bug be out for more than 72 hours if I know how to fix it.
