### ISSUE TITLE
Flight not working on v2.2.1 & v2.2.2

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#38]
It seems that the Enchantment Flight isn't working anymore on the new versions of HxCEnchants.
With v2.1.8 Flight can be activated as usual by double hitting Space. With the new versions nothing happens when I double hit the Space key.
Has there something changed?

**Comment by DrZed** [comment]
Not that I know of... You have charge?

**Comment by walkerjonny** [comment]
Yes, all armor parts are charged properly. 
As I said the Flight Enchantment works fine with the same armor parts when I downgrade to v2.1.8.
In Creative mode the Flight does also work with the new version v2.2.2 but not in Survival mode as it should. 
Have you tried it recently in Survival with the new v2.2.2?

**Comment by walkerjonny** [comment]
Thank you for fixing it!

**Comment by walkerjonny** [comment]
Sorry but the Flight Enchantment still isn't working.
I did a test with just Forge Build 1448, Optifine C1, NotEnoughItems Build 118, HxCCore 1.9.10, HxCEnchants 2.2.3, CodeChickenCore 1.0.7.47 and CodeChickenLib 1.1.3.138.
This is a very basic configuration and it still doesn't work.
I'm on Java 1.8.0_60.

**Comment by DrZed** [comment]
Update your HxCCore to 1.9.11 and it will work sorry it wasn't enchants fault...

**Comment by walkerjonny** [comment]
I'll check it out right now. Thank you!
