### ISSUE TITLE
Vitality and swiftness enchant force you out of the server

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#4]
After the update 1.2e the swiftness and vitality enchant forces you out of the server for no reason when you put them on you gear.

**Comment by DrZed** [comment]
Can you send me the server log file?

**Comment by DrZed** [comment]
BTW thank you, you're proving yourself quite helpful. Why can't every minecraft player report bugs :|

**Comment by SwornGamer** [comment]
I put it on pastebin for you so it might make it eaiser to read

http://pastebin.com/9j3f4uVL

You're welcome, I know everybody should but don't so bugs like that never get fixed.

**Comment by karelmikie3** [comment]
you made it a private post as far as I can see :/ it needs to be public for us to see.

**Comment by DrZed** [comment]
It's private http://puu.sh/hM44m.png

**Comment by DrZed** [comment]
That's amazing http://puu.sh/hM4o3.jpg

**Comment by SwornGamer** [comment]
oops my bad, it should be public now

**Comment by DrZed** [comment]
Yeah that's why I had the previous set of code now it broke unbreaking it XD

Might take me a minute I'm testing it XD

**Comment by DrZed** [comment]
give me 30 seconds I can fix it

**Comment by DrZed** [comment]
I fixed it no stutter no problems
Now wait for karel to push his fix for his stuff

**Comment by DrZed** [comment]
http://puu.sh/hM7mA.jar

**Comment by DrZed** [comment]
Close this issue if this works and the other one
because this includes both fixes

**Comment by SwornGamer** [comment]
Okay it  seems pretty good, and no problems have occurred.
