### ISSUE TITLE
Flight still not working

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#41]
Sorry but the Flight Enchantment still isn't working.
I did a test with just Forge Build 1448, Optifine C1, NotEnoughItems Build 118, HxCCore 1.9.10, HxCEnchants 2.2.3, CodeChickenCore 1.0.7.47 and CodeChickenLib 1.1.3.138.
This is a very basic configuration and it still doesn't work.
I'm on Java 1.8.0_60.

**Comment by DrZed** [comment]
You could've reopened the other one >_>

**Comment by walkerjonny** [comment]
Oh sorry. 
I didn't see the option to change it to "Open" again so I decided to open a new issue instead.

**Comment by DrZed** [comment]
Update your HxCCore to 1.9.11 and it will work sorry it wasn't enchants fault...

**Comment by DrZed** [comment]
Have fun with the latest HxCCore 1.10.0 in the repo releases :P
