### ISSUE TITLE
Enhancements: Enchants "NightView" and "Gardener"

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#42]
NightView: Better view at night like with a night vision device. -> Helmet
Gardener: Make plants grow faster within a given radius and also makes grass grow on grass blocks again. -> Helmet or Aura on all Armor parts

What do you think about that?

**Comment by DrZed** [comment]
Gaia's Aura... Gardener...
Nightview will do

**Comment by walkerjonny** [comment]
Ah, thank you! 
Wasn't sure about what Gaia's Aura is doing. The wiki does not say anything about it. Btw, if you may find some minutes just to add a little description for the newer Enchantments you have recently added to the wiki that would be fine! Maybe you want also to describe a bit about how the Aura Enchantments do work. 
As I heard, all armor parts need to have the same Aura Enchantment to make it work. Is that right?

**Comment by DrZed** [comment]
Yeah, I actually need someone to wiki for me, I'm kinda all over the place with code and stuff.

**Comment by DrZed** [comment]
specifically Gaia's Aura checks for anything growable and ticks it, I don't know if it affects grass will you check for me?

**Comment by walkerjonny** [comment]
OK, I'll check it out and report back. 
Btw, I have another Enchant in mind that might be useful when used together with Jump Boost. Because Jump Boost lets you jump quite high just stepping up one or maybe two blocks could be a bit tricky.
An Enchantment for Boots or Leggings called "Step Up" or "Autostep" that lets you automatically step up one or maybe two blocks would be useful there. Just think about it.

**Comment by walkerjonny** [comment]
Uhm, now this becomes an issue.
It seems that Gaia Aura doesn't work. I have enchanted all my armor parts with Gaia Aura on the highest level but nothing happens. The plants do not grow any faster than usual and grass doesn't grow at all.

**Comment by DrZed** [comment]
They get ticked at a certain speed

**Comment by walkerjonny** [comment]
With ticked do you mean that they should change to the next growing state immediately when they are getting ticked? 
Or do you add some kind of boost to the growing process of a plant then, for example by reducing the time required to grow to the next state?

**Comment by DrZed** [comment]
Just getting ticked, when ticked it has a 'chance' to grow.
I tick the plants faster than they are normally ticked, it's a noticable boost but not massive, I'll make it configurable so you can see if it works...

**Comment by walkerjonny** [comment]
Unfortunately we had a sudden power loss in our village while I was playing Minecraft. After the power was restored my PC didn't work anymore. It looks like my mainboard is damaged. I have ordered a new one. It should arrive on tuesday or wednesday. Until then you have to wait for results...

**Comment by DrZed** [comment]
For anyone who looks here
http://puu.sh/lnaxX.jar
v2.2.4 HxCEnchants for testing....
It has configurable rate of ticking and default double speed of normal

**Comment by walkerjonny** [comment]
So, back online now...
Tried it out with 8x but I have more the feeling that it takes somewhat longer now than usual...
Let's put together the facts about how it does work exactly:
I have all armor parts enchanted with auraGaia. How does that affect the growing speed compared to have only one armor part enchanted with auraGaia?
I have all armor parts enchanted with auraGaia Level 10. How does that affect the growing speed compared to lower levels?
I have set the speed setting to 8x. How does that affect the growing speed?
How does the addition of both auraGaia Level 10 on all armor parts and speed setting 8x affect the growing speed?

**Comment by DrZed** [comment]
1 armour doesn't trigger the event
I trigger it after doing
If (chest.hasEnchant(gaia) && helm.hasEnchant(gaia) && legs.hasEnchant(gaia) && boot.hasEnchant(gaia)) doEnchantAuraGaia();
I add the levels together 10+10+10+10 = 40
so in the event it does next random int 100/level \* multiplier
if level \* mult is over 100 it won't trigger I should fix that
Make the armour all level 3 to fix the triggering at mult 8
it should then grow exponentially fast

**Comment by walkerjonny** [comment]
So, that is how I like it.
Working together to find the reason for issue.
So either stop at Enchantment Level 3 or 4 but then the max. multiplier needs to be fixed at 100. 
I'll try it out asap. and give you a feedback.

EDIT:
Ah, I just recalculated it and decided to do the following: I reduced the multiplier to 5 and now I'm setting the armor level to 5 on all parts. Then level \* multiplier is exactly at 100.
Let's see what happens then...

**Comment by walkerjonny** [comment]
Hmm...
Didn't speed up anything at both Level 5 and 4 on all armor parts. Could you try it out for yourself? Does it work for you?

**Comment by DrZed** [comment]
Kinda on a break will look into it soon, I expect to be back in december, then will take another break on the 24th until new years

**Comment by walkerjonny** [comment]
I can wait. Take the time you need.

**Comment by ghost** [comment]
Hun, that's interesting enchantements.
