### ISSUE TITLE
Options -> Controls crash

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#43]
Hi,
this is a somewhat annoying bug.
It happens when I try to enter the "Options" -> "Controls" GUI both from the main menu or within a loaded world. This crash is repeatable and happens only when HxCEnchants 2.2.4 is added to the mods folder. 
HxCCore 1.10.0 alone works fine.
http://pastebin.com/gU1UD1XW

**Comment by DrZed** [comment]
That's an odd crash... BTW I wonder try it without super enchants, also did you delete your HxCEnchants config before updating?

**Comment by walkerjonny** [comment]
Reason was the HxCEnchants config file.
I had disabled many of the enchantments and changed the settings for some other for testing purposes. Also I didn't replace it on updating.
But there aren't any changes between the old and the new config file at all that should cause that crash normally.
Here is my modified config file:
[HxCEnchants.cfg.txt](https://github.com/HxCKDMS/HxCEnchants/files/65090/HxCEnchants.cfg.txt)

**Comment by DrZed** [comment]
What's your new file look like? I have a feeling I did change something, what version did you use previously, and what version now?

**Comment by DrZed** [comment]
Wait a sec, how did you get 2.2.4?

**Comment by walkerjonny** [comment]
You have offered it to me for testing purposes. Do you remember?
See
https://github.com/HxCKDMS/HxCEnchants/issues/42

**Comment by DrZed** [comment]
Oh, xD
