### ISSUE TITLE
Swiftness not working properly

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#44]
When Swiftness is added to the leggings and the leggings are placed in the armor slot the moving speed gets really high and stays that high even when I remove the enchanted leggings. That should not happen that way. 
Swiftness growth rates per level should be quite lower. Moving about more than two blocks at level IV with only a little hit on the movement keys is way too much. Maybe the movement speed could increase when the movement keys are pressed longer (like when you step on the gas pedal in a car). That would be much better.
And if the leggings are removed from the armer slot the swiftness effect should be removed from the player, too.

**Comment by DrZed** [comment]
Yeah, The procedural growth of speed would be quite difficult and a bit more cpu intensive requiring my enchants to update per cpu clock and on the client instead of server.

My mods I intended to be lightweight, that aside I'll work on fixing the removal issue...

**Comment by DrZed** [comment]
http://puu.sh/mdUT9.jar
Here ya go I'm releasing this version after you verify the fixes :P

**Comment by walkerjonny** [comment]
I tried the released version but as I see they are the same files.
Here are my testing results: 

Swiftness:
I tried this time only swiftness level 1. Still quite fast. I suggest to make the actual level 1 speed to level 4 speed. Maybe another level more or eventually a sixth one, but that would be more than enough in my opinion. The actual level 4 is way too fast. If you really want to keep it make it level 8 or 10 with the proper steps in between.
And removing the enchanted leggings does still not reset moving speed back to default for me.
You planned the swiftness enchantment for the leggings, right?
Because another mod has also the swiftness enchantment but for boots. I haven't activated this one to avoid double effects.
Do i need to wipe my config files to get it working?

Night Vision:
Works fine so far. Just some suggestions: 
There is no friendly name for Night Vision in the HxC Enchanter. Maybe you want to fix that.
The potion bubbles for the Night Vision enchantment make no sense in that case because it is a permanent enchantment and not a time limited one. I suggest to remove them. 

Gaja Aura:
Sorry, but for me it just doesn't seem to have any effect at all.
According to the config file the Gaja Aura Speed is at 2.5.
I have all armor parts at level 5. That should make the growth speed really fast if I remember it correctly. But the growth speed does not increase in a way that it is even recognizable.
I suggest not to work with chances only. Make the crops actually grow one level, at least one of them per round. I suggest to handle it the following way:
Level 1 to 5: Decrease the time until the the next growth round starts down to the fastest possible setting.
Level 6 to 10: Increase the number of seeds that get a guaranteed growth to the next growth level to a maximum number of 5. That should work much better.

Flight:
For some reasons it could happen after a game start (existing world), that I have to cycle through the game modes (survival, creative, adventure) including activating flight in creative at least once before flight works again in survival. That is not supposed to happen that way I think.

That is all for now.

**Comment by DrZed** [comment]
Swiftness: I decremented the increase by a ton, check the commit, But I can try finding out why it's so high,
Flight: My check for most my enchants only happens once every second I think or 10 seconds I dunno.. The disabling of the flight isn't constant either I'll look into recoding it again... (maybe make a dequip and equip event for checking)

Gaia I changed it up a bit try checking with lvl 10 on all armour

Sorry I can't disable the particles I'm using a potion effect since I can't (easily) directly modify gamma on the client. Potion particles can't be disabled in 1.7 only 1.8+

**Comment by walkerjonny** [comment]
Swiftness: At level 4 the movement speed is that fast that I'm moving somewhat between 120 to 150 blocks in just five seconds! That makes no sense. 
Level 1 Speed is ok for Level 4. It is quite fast but not too fast. 
I would suggest something like the following:
Level 1 = double speed, Level 2 = triple speed, Level 3 = quadruple speed, Level 4 = quintuple speed
And making equip and dequip events and checking there if the enchantments should still apply is a good idea. At the moment wearing a leggings with a lower swiftness level than the leggings before has no speed downgrade effect as it should have.

Gaja: OK, I'll report back.

Night Vision: I have recognized that this Night Vision is shown as "Night Vision II". Is there a "Night Vision I", too?

**Comment by walkerjonny** [comment]
Gaja with Level 10 on all armor parts:
Still no recognizable effect for me.

Could you describe your testing environment a bit?
I'm using the newest Forge 1.7.10 Build 1614, OptiFine C1 Ultra, Fastcraft 1.22 ctest17, NotEnoughIDs 1.4.0, FPS+ and BetterFps v1.0.1.
Some of those mods could cause those issues because they change essential parts of Minecraft in order to increase the overall performance significantly.  However, many people out there are using them to speed up Minecraft, especially if they are playing with many mods.

**Comment by DrZed** [comment]
My dev enviroment is Forge 1448, HxCEnchants, HxCCore, MCP Stable_12 mappings

**Comment by DrZed** [comment]
http://puu.sh/mglqJ.jar
Here I made it a configurable tweak for speed now, as well as dropped it a bit, test the new levels, and tweak to your liking...

I support optifine btw :P on the other hand not so much for fastcraft and better fps especially
Fastcraft I support depending on bug, better fps I don't know.
I guess it all depends on the bug...
Gaia enchant tweak the multiplier until you notice the effect, if nothing happens report back and I'll tripple check

**Comment by walkerjonny** [comment]
I suggest that you test your mod always with OptiFine and Fastcraft installed as both are widely used now. NEID extends the block ids to the same range that the item ids have (~ 32000) and is supported by Fastcraft. FPS+ and Better Fps do some math changes to gain higher FPS rates. They are also faster than the Fastmath option from OptiFine, which has to be turned off so that FPS+ and BetterFps can take over.

I'll test your suggestions. 
How high can I set the Gaja multiplier to have it still working with armor enchants at level 10?

**Comment by DrZed** [comment]
I can't, impossible
"I suggest that you test your mod always with OptiFine and Fastcraft installed"
They don't have open development builds...
I always use my mods with optifine on my server...
http://puu.sh/mgrcn.jpg
But as for fastcraft, I know someone who always uses it...

**Comment by walkerjonny** [comment]
Uhm, got this crash on world loading (existing world) with v2.2.5
http://pastebin.com/LeJzbj9j

Fastcraft:
You're referring to me in that case, right? ;-)

**Comment by DrZed** [comment]
Nope, Mfernflower (Mandrake Fernflower (previous coder on Minechem @MFernflower ))

**Comment by DrZed** [comment]
http://puu.sh/mgzPI.jar

**Comment by DrZed** [comment]
fixed I misspelled something

**Comment by walkerjonny** [comment]
Downloading now. 
Good to know that you have someone with coding experience helping you out on some special testing cases. 
My coding experience ends after a little bit of kix and vbs for login scripts...

**Comment by DrZed** [comment]
I have not just 1, but Myself, Karelmikie3, CodeMonkey, Wiggle1000, Domi, etc...
I code better than Mfernflower just ask him. He's just there for the kicks and giggles...

**Comment by walkerjonny** [comment]
No crash anymore. The Fix seems to work. Thank You!

Swiftness:
Works fine now. Speed is adjustable and with somewhat about 0.035 to 0.04 in a good range for Level 4.
Also equip and dequip works well now. Good work!

Gaja:
No changes even with multiplier set to 200.0 (tried 5.0, 10.0, 20.0). 
I did a test with a minimum bundle of mods to see if something interferes there.
Forge Build 1448, HxCCore, HxCEnchants, NotEnoughIDs, CodeChickenLib, CodeChickenCore.
Also I applied only the Gaja enchantment to the armor parts.
Still no change - neither with multiplier set to 2.5 or 200.0....
For me Gaja has no effect at the moment - even with that basic environment...

Repair:
Repair seems to be addicted to the default inventory slots.
One suggestion: Make it work with the additional inventory slots from Mine & Blade: Battlegear 2.
That would be a cool addition!
And in case that other enchants are also addicted to the inventory slots that applies to them, too.

**Comment by walkerjonny** [comment]
Ah, and always good to have a team/some friends around.

**Comment by DrZed** [comment]
"One suggestion: Make it work with the additional inventory slots from Mine & Blade: Battlegear 2.
That would be a cool addition!
And in case that other enchants are also addicted to the inventory slots that applies to them, too."
I'll have to look to see how the mod is coded...

**Comment by walkerjonny** [comment]
Should I continue to discuss the Gaja enchantment here or should I open a new thread for it?
And should I also open a new thread for my suggestion about Mine & Blade: Battlegear 2?

**Comment by DrZed** [comment]
#45 
#46
