### ISSUE TITLE
HxCEnchants simply not working

### ISSUE THREAD

**Issue by plazia** [HxCKDMS/HxCEnchants#47]
HxC core seems to be functioning fine but I can't get any enchants on swords working. I'm enchanting them using the xp enchanter and infusing them with levels so they are showing a charge but not one single enchant is working. I hit a mob with my sword with various hxc enchants and not one drop of charge is draining

MC 1.7.10
ForgeMultipart-1.7.10-1.2.0.345-universal
HxCCore-1.7.10-1.11.0-universal
HxCEnchants-1.7.10-2.2.4

UPDATE 2
Well I've just been testing the enchants and the armor ones actually are working but nothing I put on a sword will work. I've tried modded swords and a basic vanilla iron sword. I can put charge in it. I can even enchant it in the xp enchanter. I cannot however get it to use any charge or use any of its abilities.

UPDATE 3
Still can't sword enchants working but I have noticed a strange bug with armor. If you enchant some legs with say swiftness; then proceed to take the legs off but put them in your inventory, the effect of swiftness still persists even though you're no longer wearing the item.

**Comment by DrZed** [comment]
Sorry I forgot to upload the 2.2.5
I've had it for like 3 weeks
It's somewhere in the issues area

**Comment by DrZed** [comment]
I didn't have internet for a few days, I'm poor ya know

**Comment by plazia** [comment]
I've updated to the 2.2.5 build. For some reason my sword enchants are still not working. I've found something quite puzzling though. Normally when testing new mods I use NEI to do a dump of the used/free/all enchants. When I install your mod the resultant dumped CSV is a zero byte file. Remove your mod (HxC Core and HxC Enchants) and all of a sudden it works and I get back a 102 KiB file as expected. I know your mod does some sort of jiggery pokery to expand the enchant array/list but I'm sure something is going wrong on my setup.

I'm running 1.7.10 client and server and HxC Enchants 2.2.5 along with the most recent HxCCore 1.110

**Comment by DrZed** [comment]
I increase the max number of enchantments by 256 so that I can add lots of enchants on a whim(up to 256 enchants), NEI may not be to fond of that.
I'm currently too tired to code, but tomorrow or so I'll dig deep.

**Comment by DrZed** [comment]
Try with latest 2.3.0 build I changed a bit

**Comment by plazia** [comment]
I am now using HxCEnchants-1.7.10-2.3.2 and HxCCore-1.7.10-1.12.0-universal after being on hiatus for some time. I've noticed the armour enchants seem to work but the sword ones do nothing. I've held the item in my hand and pressed shift to ensure there is sufficient charge but nothing on the swords. As I say the armour enchants appear to be working fine.

Also after installing newest versions of the mods and renaming the existing config files to config.bak (to ensure I'm running from freshly generated configs) there is no more 0 byte enchantment.csv file.

**Comment by DrZed** [comment]
Fixed in version 2.3.3
