### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by AsHidecined** [HxCKDMS/HxCEnchants#48]
HxCCore v1.11.0 - HxCEnchants v2.2.4 - Minecraft 1.7.10 - Server forge 1448.

I keep have 2 messages when I'm connecting on my server : "[DrZed] : Sorry guys I wasn't paying attention.", "[DrZed] : Fixed the infuser crashing bug..."
When I'm saying something like "hello" in the chat, I'm disconnected "Disconnected from server" and on the console there is written : "lost connection: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: -1"

**Comment by AsHidecined** [comment]
This bug is only when I'm adding HxCEnchants v2.2.4 on the server. 
And the forge build is called "Thermos".

**Comment by karelmikie3** [comment]
can you post your fml-server-latest.log, it is found in main server directory/logs.

**Comment by AsHidecined** [comment]
I just made one because the last was empty (I didn't connect)
http://pastebin.com/P41u8LFK

**Comment by AsHidecined** [comment]
You can see I'm using 1.9.10 of the core but I tryied some others versions of HxCcore before (the latest first of course)

**Comment by karelmikie3** [comment]
I can't see any issues in here, it could be Cauldron's fault though. Do you have any other logs that may contain the error and oh yea, I should've asked before is the issue client or server side, if it is client side give me the fml client last log.

**Comment by AsHidecined** [comment]
http://pastebin.com/6WewPPfE for fml-client-latest.log
and http://pastebin.com/2YgybLB0 for latest.log (maybe it can be usefull)

**Comment by karelmikie3** [comment]
this is weird could you send me the forge/cauldron build you're using so I can try for myself.

**Comment by AsHidecined** [comment]
https://tcpr.ca/downloads/thermos (The last => Thermos-1.7.10-1614.33.zip)
The install bat tutorial http://tcpr.github.io/Thermos/install (it needs more arguments than normal to work)

**Comment by karelmikie3** [comment]
After testing I found out that HxC-Enchants isn't involved and it is most likely Thermos's fault but keep the issue open please.

**Comment by AsHidecined** [comment]
Okey no problems, thanks for your work !

**Comment by karelmikie3** [comment]
Author said it should be fixed in the latest version of Thermos, please check and if it is fixed close the issue.

**Comment by AsHidecined** [comment]
I made clean folder, download the .34 version, use the last HxC core and enchants but it's still crashing.

**Comment by DrZed** [comment]
Give me latest crash reports/logs.

**Comment by DrZed** [comment]
Make sure the version of HxCCore you used isn't for 1.8
