### ISSUE TITLE
Vitality and swiftness enchant applies to everyone

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#5]
As the title says both of those enchants applies to everyone on the server because my friend said that he got both enchant buffs but he didn't have the enchants on his armor only mine has them.

**Comment by DrZed** [comment]
wut 0_0
Can you send me his player data and yours as well I wanna investigate :D

**Comment by SwornGamer** [comment]
Okay my armor has vitality and swiftness on it when I put it on it the effects of the enchants apply to him and myself.

**Comment by DrZed** [comment]
Mkay well there is a build being made atm

**Comment by DrZed** [comment]
http://puu.sh/hS1P6.jar
Test it well my good sir :D

**Comment by DrZed** [comment]
Test it well my good sir :D

**Comment by SwornGamer** [comment]
That was quick.

**Comment by DrZed** [comment]
You bet :D

**Comment by DrZed** [comment]
Hey sam just a quick question do you use HxC-Blocks? Also do you use irc? If so join us on #HxCKDMS on irc.esper.net

**Comment by SwornGamer** [comment]
Nope, I only use HxC enchants, why do you ask?

**Comment by DrZed** [comment]
I'm about to Clean it up fix a bug and Make it more balanced :D by making it require RF temporarily (until magic energy is ready) :D

**Comment by SwornGamer** [comment]
I see, Also Zed it seems like that your update did not fix it.

**Comment by DrZed** [comment]
He has to die to reset the player attributes stored on the player data (or delete player data)

**Comment by DrZed** [comment]
Or option 3 modify the player data and remove the buffs

**Comment by SwornGamer** [comment]
I'm going to slay him to fix it

**Comment by DrZed** [comment]
Have fun xD

**Comment by SwornGamer** [comment]
uhhh that didn't work.

**Comment by DrZed** [comment]
:I I'll take another look but I got a new enchant coming soon :D Divine Intervention if health is less than a certain amount and player takes lethal damage they get tp'd to their spawn (bed usually), the enchant gets removed, and the damage is cancelled (or absorbed by armour configurable)

**Comment by SwornGamer** [comment]
It seems like every enchant applies to everybody not just those two, I just tried to kill him and the regen enchant shot him back to full life. I think this bug is a lot bigger then what I realize. Also that sounds like an awesome enchant.

**Comment by DrZed** [comment]
I need to do a little bit of investigation I think I have more sleep drunk code
VERY MUCH SLEEP DRUNK CODE

**Comment by DrZed** [comment]
http://puu.sh/hS7lg.jpg
Also you now won't need to kill him to clear it
http://puu.sh/hS7rv.jar
