### ISSUE TITLE
Enchant "Overcharge" not working

### ISSUE THREAD

**Issue by shaqallen314** [HxCKDMS/HxCEnchants#51]
Sorry to bother you guys, but I have a important question about HxC enchantment mod.
There is a enchantment called "Overcharge", and from the explanation, we can know that it is a powerful enchantment.
But I tried a lot of times with different ways, I have the enchantment on my iron sword, and just like other enchantment,
I press G for charge. When I kill mob with this sword, it consumes charge, but I don't see any effect of "distribute damage to all nearby enemy."
Then I found something in minecraft controls called "Overcharge", and it's keybind is O. So in game I press O, Nothing happen Q_Q.

I'm wondering which step goes wrong, I really hope friends here can tell me How to use this enchantment correctly.

Minecraft version:1.7.10
Forge version:10.13.4.1614
HxC core version:1.7.10-1.13.2 universal
HxC enchantment version:1.7.10-2.5.0

Thanks a lot!

**Comment by DrZed** [comment]
Ok how it's supposed to work is via charge, you need charge. It consumes charge from the charges to build up damage, then when the key is pressed again it stores that charge as damage. Then the next time you attack something, it distributes the bonus damage to all enemies in an area.

**Comment by shaqallen314** [comment]
So I should press G(default "XP to charges" key) to make my weapon has charges, and then I press O(default "overcharge" key) to consume charges in it. At this time, the weapon's charge should decrease, right?
And when the charges consumes, I press O again, then attack.

Is the all above correct?

**Comment by shaqallen314** [comment]
I tried the method I described above, still no effect O_O

**Comment by DrZed** [comment]
should
but that's assuming I didn't get some numbers wrong somewhere
I'll look at it soon-ish

**Comment by shaqallen314** [comment]
Does the mod works well?

**Comment by DrZed** [comment]
yes
