### ISSUE TITLE
ClassNotFoundException: hxckdms.hxCConfig.HxCConfig

### ISSUE THREAD

**Issue by Tcll** [HxCKDMS/HxCEnchants#52]
just updated to 3.0.0 (core 2.0.6) from 2.5.0 (core 1.13.2) to fix the perma Swiftness issue after removing the enchant.

it shows the Minecraft window and crashes shortly after.

here's my crash log for the extra info:
https://mega.nz/#!o0x02DJB!UdanKsT8d6uAfjFch2HKvYiTcgWcLK9FVEw_EnApQZc

sorry if you don't like mega, I refuse to use Dropbox anymore, and don't find Pastebin worth the effort.
I would use a gist if copying weren't so difficult on a phone.

**Comment by DrZed** [comment]
You need to use HxCCore 2+ with HxCEnchants 3+
NVM you are... I'm in the middle of a rewrite as you can probably see so I cannot guarentee the quality of this next update As this will be an update before my complete rewrite of the code.

**Comment by Tcll** [comment]
2.0.6 (as noted) is the latest for 1.7.10
I wouldn't be reporting otherwise ;)

EDIT:
Thanks for the quick response btw :D

**Comment by DrZed** [comment]
It's been uploaded to curse just waiting for approval

**Comment by Tcll** [comment]
3.0.1
literally the same issue

**Comment by DrZed** [comment]
I tested it myself and didn't have the issue, I wonder how this occurs
Do you have ConfigurationAPI-1.3.jar in your mods/1.7.10 folder

**Comment by DrZed** [comment]
Just took 3 shots of rum so not gonna make any progress in code tonight or I might fudge something up even more.

**Comment by Tcll** [comment]
oh I didn't know that was required (or is it?), I can grab it real quick and give it a test ;)
I'd figured it worked for you or you wouldn't be releasing, so yeah I'm sure it's something I don't have.

EDIT: oh I thought it was a mod.
I'm building my modpack off an ATL server, which I'm not sure what type of server it is, but I can tell you there's no plugins folder. fu
in any case, it crashes both the client and server with the same error.
I was only focusing on the client, once the client works, I can test the server.

EDIT2: just re-read and yes it is a mod
not sure what Google is smoking...

EDIT3: yeah I can't seem to find a download for it...
I found a code, but it has 0 releases...
really don't feel like setting up a gradle environment just to build it...
(I'm offline, so I have to install a zip of one I've downloaded manually)

**Comment by DrZed** [comment]
It's not a mod it's our config api that karel created for use with anything java related (my skype bot uses it as well as my rule 34 application (further information is on LostPotatoFoundation's github nothing more will be said about it here)).

As for the actually having it, it auto downloads from github so it's a simple yes or no if it is in the folder or not. If not download it from our github page for ConfigurationAPi and stick it in mods/1.7.10.

**Comment by DrZed** [comment]
![2017-09-07_22-46-24](https://user-images.githubusercontent.com/5124544/30194102-2dcf3c16-941f-11e7-8500-8e4afda05915.png)

**Comment by Tcll** [comment]
oh ok, should probably note that or include a default version with the mod, since I don't have internet. ;)

I had no idea

**Comment by DrZed** [comment]
https://github.com/HxCKDMS/ConfigurationAPI/releases
Stick latest version in mods/1.7.10

**Comment by Tcll** [comment]
just to confirm, it works!
I'm at the title screen =D
