### ISSUE TITLE
Please add Saturation :)

### ISSUE THREAD

**Issue by Tcll** [HxCKDMS/HxCEnchants#53]
Saturation is an armor or item effect that replenishes your hunger without the need for food.

I was honestly surprised when I found out this mod didn't have an enchant of this effect.
I've found many bukkit plugins that​ make the Saturation enchant, but not one mod.

there's mods like Artifacts or Magical Crops that strictly use their own versions of armor with the effect, but I've never seen an enchant.

EDIT:
also, yes I'm​ aware of gluttony, which is similar, but needs food.

**Comment by DrZed** [comment]
Sure I'll make it incompatible with gluttony.

**Comment by Tcll** [comment]
I just had an interesting idea for this

normally Saturation keeps your hunger at max no matter how much energy you exert.
(Zivicio pickaxe with veinminer)

but my idea was to level it up to like Saturation III or so, where each lower level would have a longer replenishment delay and interval.
the max level of course being the original effect result.

I'm interested to hear your input on that :D

**Comment by DrZed** [comment]
I'm gonna do it like regen enchant works, config delay with enchant level added food per activation.

**Comment by Tcll** [comment]
if food can be disabled, that would be cool ;)
I like the option though for those strict hardcore server owners ;D

**Comment by DrZed** [comment]
Completed

**Comment by Tcll** [comment]
ok so I just tried Saturating V on my bow since it wasn't available for any of the armor pieces...
it's too slow to equate to Saturation as requested, I had to do `/gamemode 1` because I nearly died waiting for at least 1 hunger bar to fill during my test.

basically, compair Saturating V to a healing axe.
Magical Crops Ultimate Armor with a saturation gem is faster I think...

basically, the test I do is infinite veinminer on stone and see how long I can vm before I get stopped by hunger...
with Ultimate Armor, it never drops a bar
I would assume a healing axe would be the same, but of course I can't test it while veinmining...

hey it seems to be progress though, so keep up the good work ;)
also, I like the name change to prevent effect confusion ;D

**Comment by Tcll** [comment]
ok so I haven't found the offending mod yet, but I can confirm I do have it working after removing everything but OC and waila (and associates)...
something I did notice though was that, during game lag on placement, the names cycled through like the video above before the lag cleared and the name was decided...

think that might give you guys a lead to fix the random name generator to make sure a name is only generated once??
or is it something deep down in the registration that may be causing the later decision??

**Comment by DrZed** [comment]
My bad I did a dumb It's supposed to go on helmet, fix in configs... Will update myself

**Comment by DrZed** [comment]
Change the type from 6 to 5 for saturation enchant

**Comment by Tcll** [comment]
sorry for that last message, that was a response for here:
https://github.com/MightyPirates/OpenComputers/issues/2510
(your mod isn't a cause btw) ;)

but alright I'll do that :)

**Comment by DrZed** [comment]
My saturation should be relatively fast but not instant, I believe 5 seconds between activations

**Comment by Tcll** [comment]
that sounds like my thoughts for Saturating I (5 or 7 seconds)
Saturating V should be the same as a healing axe. (and expensive to apply)

is this configurable??

**Comment by DrZed** [comment]
always

**Comment by Tcll** [comment]
alright cool, so I won't have to bug ya so much about the little things ;)

but I was hoping my Saturating thoughts could be applied globally,
because the Saturation effect across mods is typically fast.

I think Artifacts for 1.6.4 was the slowest, though I can't remember how slow... (I think 1 second intervals)
it was faster in newer versions, but I had magical crops, so I never used it... :P 
my point though is it's fast, and your mod might get flamed for being defaultly slow.

**Comment by DrZed** [comment]
I don't like the idea of not needing food I even install Pam's Harvestcraft and farm the ingredients to make pizza's.

**Comment by Tcll** [comment]
haha, I guess that'll be an endless war of preference between us then XD
(that's what Saturation is tho :P)

I don't have Magical Crops armor and I'm trying not to add it because I want to keep the base initialization of the world under 3GB of RAM use,
and I'm doing good so far with everything I have.
I miss FastCraft T_T

EDIT:
you could just disable it by default...
it's your mod, so your preference takes priority over the possibly greater preference of everyone else ;)
