### ISSUE TITLE
Vitality enchant acts like swiftness enchant

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#6]
It seems like as the title says that vitality isn't doing what it's supposed to be doing but instead acts like the swiftness enchant and the swiftness enchant doesn't do anything.

**Comment by DrZed** [comment]
Are you using latest version from Curse Forge?

**Comment by SwornGamer** [comment]
Yes I am

**Comment by DrZed** [comment]
Epic Fail is epic

**Comment by DrZed** [comment]
Thank you a lot even if you can't code you must admit this was obvious
http://puu.sh/hVsH5.png

**Comment by SwornGamer** [comment]
I can code a little bit but nothing java, but yeah that is obvious.

**Comment by DrZed** [comment]
Here ya go
http://puu.sh/hVsSG.jar

**Comment by SwornGamer** [comment]
thank you.

**Comment by DrZed** [comment]
@EnderSam Are you still around? If so I have a new build for you to play with.

**Comment by DrZed** [comment]
http://puu.sh/jbjEk.jar

**Comment by DrZed** [comment]
Configs must be deleted before using this build

**Comment by SwornGamer** [comment]
Yeah, I'm still around

**Comment by DrZed** [comment]
So would you test :P also I need a better way to contact you for testing if you want to test :P also this version has 2 new enchants, Slayer's Curse and Vorpal

**Comment by SwornGamer** [comment]
Alright. do you have any ideas we could keep in contact better? I mean I have skype but not sure if you want to give yours out, that is if you do have one

**Comment by DrZed** [comment]
ケルドンスレイヤー search skype directory for that <

**Comment by SwornGamer** [comment]
I found you.
