### ISSUE TITLE
New Enchant

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#7]
This isn't an issue, per say. I just had a suggestion for an enchant that the mod More Enchantments by Lithial (found here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1445082-more-enchantments-version-1-3-now-for-1-8) used to have in their mod, but took out.

It was a Piercing enchant (I forgot the name) but it ignores armor and is used on swords and bows. I'm using mods like Chocolate Quest, Rogue-like Dungeons, Special Mobs and the mobs have increasingly heavier sets of armor. I'd love an enchant that can ignore more armor the higher the enchant as the normal sharpness enchant can only do so much damage. I'll be fighting a diamond armor zombie and it also is an "Infernal Mob" (another mod that adds values to mobs at random, more HP, stronger etc.) that has 100HP and I do 1 damage with the highest enchants on a sword. Not including poison/wither/fire etc.

Great job on the mod by the way. I absolutely love it.

**Comment by DrZed** [comment]
I will look into it but I will have a damage reduction for what penetrates somewhere around 30% maybe configurable :P

**Comment by ReportBot9009** [comment]
Yes, that was the name, Penetration! Yes, maybe configurable for armor type? The enchant works less on stronger armor? 

Anything configurable in the configs is a win for me!

I do miss that enchant and thought your enchant mod is waaay more active than the others. ;) Great job on that and everything else. 

Wow, thanks for the reply :)

**Comment by DrZed** [comment]
I update the moment I get a new Idea or bug so yeah of course I'm more active

**Comment by ReportBot9009** [comment]
Haha, you are indeed! Awesome, I'll be watching for updates if you decide to implement this. Thanks again!

**Comment by DrZed** [comment]
implementing now :P

**Comment by DrZed** [comment]
Implemented go grab the update when curse forge accepts my latest build

**Comment by DrZed** [comment]
http://puu.sh/hVxIR.jar

**Comment by DrZed** [comment]
version 1.4 curse is taking forever

**Comment by ReportBot9009** [comment]
Haha, I was wondering what's the normal update time. You did this so fast for me, I can be patient.

**Comment by DrZed** [comment]
approved

**Comment by DrZed** [comment]
go grab it :P

**Comment by ReportBot9009** [comment]
It's not updated for me yet, lol!

**Comment by ReportBot9009** [comment]
Hmmm, just tried it now. I put Piercing on a diamond sword lvl 10 and had a normal diamond sword and found an armored zombie. There was no damage change between the two. Did 3 damage with both swords.
