### ISSUE TITLE
Vitality and swiftness enchant broken (Again)....

### ISSUE THREAD

**Issue by SwornGamer** [HxCKDMS/HxCEnchants#8]
Dr.Zed it seems like nether enchant are working the way they are supposed to. I already killed myself to make sure that wasn't the case and it wasn't but I also reapplied the enchants and nothing happened. I just wanted to test a couple of things first before reporting it to you.

**Comment by DrZed** [comment]
Welp sorry again next time just re-open a previous one but i just re-arranged the code to hopefully make it work as intended and I added a few more enchants

**Comment by DrZed** [comment]
updated CurseForge

**Comment by DrZed** [comment]
updating curse
Let me know if that fixed it I'm not closing until verified
http://puu.sh/hVwuA.png

**Comment by SwornGamer** [comment]
It shows on my screen that there isn't anything for HxCEnchants for Curse forge

**Comment by DrZed** [comment]
Did you look at that picture XD
http://puu.sh/hVwD3.jar
Here so you don't have to wait lel

**Comment by SwornGamer** [comment]
Are you talking about the one for the coding mistake? because if you are I did and I laughed about it

**Comment by DrZed** [comment]
Nah it was the other newer 1 http://puu.sh/hVwuA.png

**Comment by SwornGamer** [comment]
intresting

**Comment by DrZed** [comment]
still under review :I

**Comment by DrZed** [comment]
Getting my morning coffee I really need it

**Comment by SwornGamer** [comment]
It's afternoon for me and I always need more coffee.

**Comment by SwornGamer** [comment]
Dr.zed it seems like you made a mistake by not adding the new enchant to the HxC Enchants config so it defaults to Enchantment Id 0 which is already taken so I can't continue to test if you had fixed it

**Comment by DrZed** [comment]
Thanks uploading fix
sorry :I REALLY NEED MY COFFEE

**Comment by DrZed** [comment]
http://puu.sh/hVxIo.jar

**Comment by DrZed** [comment]
So far working or broken?

**Comment by SwornGamer** [comment]
haven't gotten a chance to check because I wasn't at my computer, so I'm going to check right now.

**Comment by SwornGamer** [comment]
Not been fixed

**Comment by DrZed** [comment]
What mods do you have installed
I wonder if there is one that plays with monster attributes as well

**Comment by DrZed** [comment]
http://puu.sh/hVDu6.jar
I tested this should work
Previous didn't work

**Comment by SwornGamer** [comment]
Yes, there you go it's fixed, Good Job. _thumbs up_

**Comment by DrZed** [comment]
Lol it only took me what 30 tries?

**Comment by SwornGamer** [comment]
Well it works now and that's what matters the most

**Comment by DrZed** [comment]
lol

**Comment by karelmikie3** [comment]
good josh!

**Comment by DrZed** [comment]
joj karel
not josh
