### ISSUE TITLE
Enchant ID Crash

### ISSUE THREAD

**Issue by ReportBot9009** [HxCKDMS/HxCEnchants#9]
I'm not sure if this is working correctly... I've tried with different swords and armored mobs. Same damage across all swords and all enchantment levels.

**Edit

I mean to add that I am using a pretty extensive custom modpack. Just for myself. It includes 233 total mods so far, but all of your enchants work just fine.

I did have another suggestion for the enchantment IDs. Whenever I try to change the IDs from something other than what they are in configs, the game crashes. I was wondering if you could open up ID Value range, because when in game, sometimes to test things out, I use the NEI Enchant screen and your ID values are so far up (400 range) that NEI doesn't register them. I can only put your enchants on with Enchanting Plus's modded enchanting table. Unless you want me to open an issue with CodeChicken at NEI.

Thanks again :)

**Comment by DrZed** [comment]
Give me your crash report I believe you tried to move the id to something too low or too high (low being used)

**Comment by ReportBot9009** [comment]
Ok, here is the crash:

http://pastebin.com/Zx32nWcU

This crash happened from changing the default IDs from their ~400 to the twenties. I did and NEI Enchantment dump and I had open ID values from 22-31. So I put a couple of your enchants in that range and that is where the crash comes in.

Sorry it took a while to get back to you.

**Comment by DrZed** [comment]
Not my fault
Don't move the IDs I made them not apply-able with NEI
Those are safe IDs I moved them 400+ because conflicts with other IDs these are only used by me so they'll never conflict by default

**Comment by DrZed** [comment]
Delete your configs let the mod auto-regenerate them It'd be fine
